#define TK_PLUS                            1
#define TK_MINUS                           2
#define TK_STAR                            3
#define TK_SLASH                           4
#define TK_PERCENT                         5
#define TK_NEWLINE                         6
#define TK_ID                              7
#define TK_ASSIGN                          8
#define TK_PRINT                           9
#define TK_END                            10
#define TK_ELSE                           11
#define TK_REPEAT                         12
#define TK_UNTIL                          13
#define TK_IF                             14
#define TK_WHILE                          15
#define TK_LPAREN                         16
#define TK_RPAREN                         17
#define TK_NUMBER                         18
