#define TK_LESS                            1
#define TK_EQUALS                          2
#define TK_PLUS                            3
#define TK_MINUS                           4
#define TK_STAR                            5
#define TK_SLASH                           6
#define TK_PERCENT                         7
#define TK_NEWLINE                         8
#define TK_STRING_TYPE                     9
#define TK_NUMBER_TYPE                    10
#define TK_BOOLEAN_TYPE                   11
#define TK_FUNCTION                       12
#define TK_ID                             13
#define TK_END                            14
#define TK_LPAREN                         15
#define TK_RPAREN                         16
#define TK_COMMA                          17
#define TK_ASSIGN                         18
#define TK_PRINT                          19
#define TK_RETURN                         20
#define TK_IF                             21
#define TK_ELSE                           22
#define TK_WHILE                          23
#define TK_DO                             24
#define TK_NUMBER_VALUE                   25
#define TK_STRING_VALUE                   26
#define TK_BOOLEAN_VALUE                  27
