#define TK_PLUS                            1
#define TK_MINUS                           2
#define TK_STAR                            3
#define TK_SLASH                           4
#define TK_PERCENT                         5
#define TK_NEWLINE                         6
#define TK_ID                              7
#define TK_ASSIGN                          8
#define TK_PRINT                           9
#define TK_LPAREN                         10
#define TK_RPAREN                         11
#define TK_NUMBER                         12
