#define TK_LESS                            1
#define TK_PLUS                            2
#define TK_MINUS                           3
#define TK_STAR                            4
#define TK_SLASH                           5
#define TK_PERCENT                         6
#define TK_NEWLINE                         7
#define TK_FUNCTION                        8
#define TK_ID                              9
#define TK_LPAREN                         10
#define TK_RPAREN                         11
#define TK_END                            12
#define TK_COMMA                          13
#define TK_ASSIGN                         14
#define TK_PRINT                          15
#define TK_RETURN                         16
#define TK_IF                             17
#define TK_ELSE                           18
#define TK_WHILE                          19
#define TK_DO                             20
#define TK_NUMBER                         21
#define TK_STRING                         22
