#define TK_LESS                            1
#define TK_EQUALS                          2
#define TK_PLUS                            3
#define TK_MINUS                           4
#define TK_STAR                            5
#define TK_SLASH                           6
#define TK_PERCENT                         7
#define TK_NEWLINE                         8
#define TK_FUNCTION                        9
#define TK_ID                             10
#define TK_LPAREN                         11
#define TK_RPAREN                         12
#define TK_END                            13
#define TK_COMMA                          14
#define TK_ASSIGN                         15
#define TK_PRINT                          16
#define TK_RETURN                         17
#define TK_IF                             18
#define TK_ELSE                           19
#define TK_WHILE                          20
#define TK_DO                             21
#define TK_NUMBER                         22
#define TK_STRING                         23
#define TK_BOOL                           24
